### ISSUE TITLE
Unable to add a station 

### ISSUE THREAD

**Issue by Shredder5262** [fivebanger/kodi_addons#12]
I've been using this plugin for about 10 minutes, so far, great work! I have been having trouble adding a station to my stations list that i was not able to search for... Everything looks correct to me via the stations file, but i get an error when trying to select the station...not sure what I'm doing wrong, please help.

{"data": {"id": "hyruleradio","name":"Hyrule Radio","icon_url":"https://pbs.twimg.com/profile_images/457621656781852673/ueKdsl9D_400x400.png","stream_url":"http://listen.radiohyrule.com:8000/listen"},"mode": "play_stream"}

I am not able to spot the obvious error in the logs...., but the behavior that occurs is that the next radio station in line plays instead of playing the selected station that I've posted above.

**Comment by fivebanger** [comment]
The stream "Hyrule Radio" you are attempting to play seems not to be available on Radio.de. Pls. check with your browser and open: 
```
https://www.radio.de/search?q=Hyrule%20Radio
```

Also addressing the station directly in the browser does not work:
```
https://www.radio.de/s/hyruleradio
```

The addon tries to resolve the id=hyruleradio. If this id is unknown by Radio.de, the stream won't play.

If you want to add a station by your own as a custom station (which then gets not resolved by the Radio.de API), pls. follow https://github.com/fivebanger/kodi_addons/tree/master/plugin.audio.radiode#custom-stations. You can e.g. edit the `stations.jsn-file` (like you have already done) and keep the "id"-field empty (see https://github.com/fivebanger/kodi_addons/tree/master/plugin.audio.radiode#edit-stationsjsn ). Otherwise the addon tries to resolve what's given by "id".

**Comment by Shredder5262** [comment]
AH! Perfect! Having "id": "hyruleradio" was the issue, once I removed the id to be blank, BOOM! works. Thank you! Please mark this as solved.

**Comment by fivebanger** [comment]
Solved and closed.
