### ISSUE TITLE
Calling custom station via json RPC call 

### ISSUE THREAD

**Issue by Shredder5262** [fivebanger/kodi_addons#14]
Sorry but I have another question as a continuation of https://github.com/fivebanger/kodi_addons/issues/12

I was able to get the custom station to work, but I need to be able to call it from home assistant which I understand to use the path 
plugin://plugin.audio.radiode/?mode=play_station&data=%7B%22id%22%3A+%223%22[stationid]%7D
But in this case the id is blank...so how do i call the custom station in this case? i've tried a few things, but I'm just guessing. What is the correct way to do this?

**Comment by fivebanger** [comment]
Your path is wrong at least and should be:
```
plugin://plugin.audio.radiode/?mode=play_station&data=%7B%22id%22%3A+%22{stationid}%22%7D
```

If you want to call from JSON-RPC, you have to apply a station_id in that case. I.e., you cannot call this method with a custom station (without an station_id) because the add-on is not able to get the station's URL in that case. In order to get a station URL you need a station_id.

There is also a way to call the radio add-on by using a custom station. But you have to call the add-on in another way in that case (you can enable "logging" in Kodi to see how to call the related path).

As mentioned already here https://github.com/fivebanger/kodi_addons/issues/3, the add-on call always uses a html quoted JSON structure. For calling a custom station you have to call the addon using mode=play_stream and use a valid html quoted JSON structure which contains the station's link. You can find exactly that call when enabling "logging" and check the log.

The ?mode=play_station function was just a shortcut and convenience function to be able to call the add-on from JSON-RPC side in an more convenient way.

**Comment by fivebanger** [comment]
As a hint: the JSON struct that's required for a custom station JSON-RPC call is the struct you already have in the `jsons.jsn` file for a custom station, e.g.:
```
{"id": "", "name": "ROCK ANTENNE", "icon_url": "https://d3kle7qwymxpcy.cloudfront.net/images/broadcasts/31/87/9112/4/c300.png", "stream_url": "https://stream.rockantenne.de/rockantenne/stream/mp3?aw_0_1st.playerid=radio.de"}
```
Generate a html-quoted string from that structure and call the add-on with 
```
plugin://plugin.audio.radiode/?mode=play_stream&data=HTML_QUOTED_JSON_STRNG
```

I have not tried by use of JSON-RPC but that's at least the idea behind...

**Comment by Shredder5262** [comment]
Ok, yep, I was able to find this object in the logs after reading your message, tried it and it worked. There is absolutely no way I would have been able to figure that out without your previous message; thank you for that. 

2024-11-20 08:32:54.589 T:28796   debug <UPNP::BuildObject>: Building didl for object 'plugin://plugin.audio.radiode/?mode=play_stream&data=%7B%22id%22%3A+%22%22%2C+%22name%22%3A+%22Hyrule+Radio%22%2C+%22icon_url%22%3A+%22https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F457621656781852673%2FueKdsl9D_400x400.png%22%2C+%22stream_url%22%3A+%22http%3A%2F%2Flisten.radiohyrule.com%3A8000%2Flisten%22%7D'


This was the object path I had to use in home assistant to play the radio station 
plugin://plugin.audio.radiode/?mode=play_stream&data=%7B%22id%22%3A+%22%22%2C+%22name%22%3A+%22Hyrule+Radio%22%2C+%22icon_url%22%3A+%22https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F457621656781852673%2FueKdsl9D_400x400.png%22%2C+%22stream_url%22%3A+%22http%3A%2F%2Flisten.radiohyrule.com%3A8000%2Flisten%22%7D
