### ISSUE TITLE
Addon crashes in Linux Mint, in Windows it works fine

### ISSUE THREAD

**Issue by Rizado** [fivebanger/kodi_addons#5]
When I try to run this addon I can can do it only in Windows, But my main OS for work is Linux Mint 22 (with Linux Mint 21.3 addon crashes too, I checked this).
I don't have any suggestions about possible reasons.
I add log files from Kodi, checked with Python 3.10, 3.12 and 3.13.

[kodi_crashlog-20240804_155949.log](https://github.com/user-attachments/files/16487632/kodi_crashlog-20240804_155949.log)
[kodi_crashlog-20240804_160039.log](https://github.com/user-attachments/files/16487633/kodi_crashlog-20240804_160039.log)
[kodi_crashlog-20240804_160125.log](https://github.com/user-attachments/files/16487634/kodi_crashlog-20240804_160125.log)

**Comment by Rizado** [comment]
Update. This addon works fine with Kodi 19.4 under Linux Mint 21.3 and with Kodi 21 under WIndows 11, but doesn't work with Kodi 20.5 under Linux Mint 22. Version of Kodi is latest from repos of Linux Mint.

**Comment by fivebanger** [comment]
1. Which AddOn from the repository you are referring to?
2. In any case: The crash logs does not provide helpful information since the # LOG FILE # does not contain any information with respect to an AddOn failure and the # STACK TRACE # section is Kodi and OS dependent, no idea how to map these info to an AddOn error.

Maybe you can "enable debug logging" in Kodi's system menu and provide the "kodi,log" file in case of error.

**Comment by fivebanger** [comment]
Update: The crash-log shows an important line

#6  0x00007748266f3f58 in _Py_FatalErrorFunc () from /lib/x86_64-linux-gnu/libpython3.12.so.1.0

While searching the WWW it turned out that Kodi 20.5 doesn't work on systems using Python 3.12 (see https://github.com/retrospect-addon/plugin.video.retrospect/issues/1819). A combination of Kodi 20.5 and Ubuntu 24.04 (which is the basis for Linux Mint 22) leads to an crash when starting an AddOn.

see also:
https://github.com/retrospect-addon/plugin.video.retrospect/issues/1819
https://bugs.launchpad.net/ubuntu/+source/kodi/+bug/2063358
https://github.com/xbmc/xbmc/issues/24069

All reported issues shows the same _Py_FatalErrorFunc failure in conjunction with libpython3.12.so.1.0.

There is nothing the AddOn developer can do in order to fix this issue.

**Comment by Rizado** [comment]
> * Which AddOn from the repository you are referring to?
I´m sorry. But now you understood this without me.

OK, I´ll wait for new version of Kodi. There is no PPA for Ubuntu 24.04/Mint 22 now.
And now I listen online radio using browser, but Kodi and your addon is better.

**Comment by fivebanger** [comment]
> OK, I´ll wait for new version of Kodi. There is no PPA for Ubuntu 24.04/Mint 22 now. 

I have installed Mint 22 on a VirtualMachine. Installing Kodi from from regular software manager ended up in an error message. But installing Kodi from flathub.org as a flatpak has worked without any issue. Latest Kodi 21 is installed when downloading from flathub.org. Also installing and running the radio.de AddOn has worked without problems.

Maybe you can give it a try to install Kodi from flathub on your Linux Mint 22.

**Comment by fivebanger** [comment]
No Radio.de addon issue. Close as completed.
